<?php

namespace Proxies\__CG__\BaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CruiseShipCabinType extends \BaseBundle\Entity\CruiseShipCabinType implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'id', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtId', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'placeCountMax', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtName', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtComment', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'cabins'];
        }

        return ['__isInitialized__', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'id', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtId', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'placeCountMax', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtName', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'rtComment', '' . "\0" . 'BaseBundle\\Entity\\CruiseShipCabinType' . "\0" . 'cabins'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CruiseShipCabinType $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRtId($rtId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRtId', [$rtId]);

        return parent::setRtId($rtId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRtId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRtId', []);

        return parent::getRtId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRtName($rtName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRtName', [$rtName]);

        return parent::setRtName($rtName);
    }

    /**
     * {@inheritDoc}
     */
    public function getRtName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRtName', []);

        return parent::getRtName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRtComment($rtComment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRtComment', [$rtComment]);

        return parent::setRtComment($rtComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getRtComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRtComment', []);

        return parent::getRtComment();
    }

    /**
     * {@inheritDoc}
     */
    public function addCabin(\BaseBundle\Entity\CruiseShipCabin $cabins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCabin', [$cabins]);

        return parent::addCabin($cabins);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCabin(\BaseBundle\Entity\CruiseShipCabin $cabins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCabin', [$cabins]);

        return parent::removeCabin($cabins);
    }

    /**
     * {@inheritDoc}
     */
    public function getCabins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCabins', []);

        return parent::getCabins();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceCountMax($placeCountMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceCountMax', [$placeCountMax]);

        return parent::setPlaceCountMax($placeCountMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceCountMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceCountMax', []);

        return parent::getPlaceCountMax();
    }

}
