admin:
   resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
   prefix: /admin

_sonata_admin:
   resource: .
   type: sonata_admin
   prefix: /admin



homepage:
    path: "/"
    defaults: { _controller: BaseBundle:Document:index }

specialoffer:
    path: "/specialoffer/{offer}.html"
    defaults: { _controller: BaseBundle:Cruise:specialoffer }

cruisedetails:
    path: "/cruise/cruisedetails/{url}.html"
    defaults: { _controller: BaseBundle:Cruise:details }	

monthschedule:
    path: "/cruise/monthschedule"
    defaults: { _controller: BaseBundle:Cruise:schedule }

month_cruises:
    path: "/cruise/month/{month}.html"
    defaults: { _controller: BaseBundle:Cruise:month }

page:
    path: "/{first}/{second}/{name}.html"
    defaults: { _controller: BaseBundle:Document:page }

search:
    path: "/search"
    defaults: { _controller:BaseBundle:Cruise:search }

page_small:
    path: "/{first}.html"
    defaults: { _controller: BaseBundle:Document:page }		

classlist:
    path: "/cruise/classlist"
    defaults: { _controller: BaseBundle:Ship:classlist }

alphabetlist:
    path: "/cruise/alphabetlist"
    defaults: { _controller: BaseBundle:Ship:alphabetlist }

showDocuments:
    path: "/{first}/{second}/"
    defaults: { _controller: BaseBundle:DocumentCategory:documents }	


base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /
