security:

    providers:
        main:
            entity: { class: BaseBundle:User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                check_path: _security_check
                login_path: _security_login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        BaseBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10