<?php

namespace BaseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class DocumentRepository extends EntityRepository
{
	public function findForSiteMap() {
		$str = "SELECT d
			FROM BaseBundle\Entity\Document d
			WHERE  d.archieved = 0
			";
   		$q = $this->_em->createQuery($str);
   		return $q->getResult();
	}
}	