<?php

namespace Proxies\__CG__\BaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentCategory extends \BaseBundle\Entity\DocumentCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'documents', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'id', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'title', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'description', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'level', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'ord', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'baseurl', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'deletable', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'parent'];
        }

        return ['__isInitialized__', 'documents', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'id', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'title', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'description', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'level', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'ord', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'baseurl', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'deletable', '' . "\0" . 'BaseBundle\\Entity\\DocumentCategory' . "\0" . 'parent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocumentCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel($level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrd($ord)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrd', [$ord]);

        return parent::setOrd($ord);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrd', []);

        return parent::getOrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseurl($baseurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseurl', [$baseurl]);

        return parent::setBaseurl($baseurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseurl', []);

        return parent::getBaseurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletable($deletable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletable', [$deletable]);

        return parent::setDeletable($deletable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletable', []);

        return parent::getDeletable();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\BaseBundle\Entity\DocumentCategory $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\BaseBundle\Entity\Document $documents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$documents]);

        return parent::addDocument($documents);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\BaseBundle\Entity\Document $documents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$documents]);

        return parent::removeDocument($documents);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

}
